const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');
const screenUi = document.getElementById('screenUi');
const startButton = document.getElementById('startButton');
const scoreEl = document.getElementById('score');
const highScoreEl = document.getElementById('highScore');
const waveEl = document.getElementById('wave');
const shieldEl = document.getElementById('shield');
const weaponEl = document.getElementById('weapon');
const bossReadout = document.getElementById('bossReadout');
const bossNameEl = document.getElementById('bossName');
const bossPercentEl = document.getElementById('bossPercent');
const bossBarFill = document.getElementById('bossBarFill');

const W = canvas.width;
const H = canvas.height;
const keys = {};
const colors = { mint:'#8ef5da', orange:'#ff9b5b', red:'#ff5a6f', blue:'#63a5ff', white:'#e9fff8' };
let game;
let highScore = Number(localStorage.getItem('sky-vector-high-score') || 0);
highScoreEl.textContent = String(highScore).padStart(6, '0');

function createGame() {
  return { active:true, paused:false, endingMs:0, score:0, stage:1, wave:1, shield:3, weapon:1, elapsed:0, enemyTimer:0, groundTimer:0, boss:null, bossSpawned:false, bullets:[], enemyBullets:[], enemies:[], groundTargets:[], pickups:[], particles:[], texts:[], stars:makeStars(), player:{x:W/2,y:H-90,w:25,h:30,cooldown:0,invincible:0}, bombFlash:0 };
}
function makeStars() { return Array.from({length:70}, () => ({x:Math.random()*W,y:Math.random()*H,s:Math.random()*1.7+.3,v:Math.random()*35+18,a:Math.random()})); }
function startGame() { game=createGame(); screenUi.classList.remove('victory'); screenUi.querySelector('.screen-tag').textContent='MISSION // AIRSPACE'; screenUi.querySelector('.title-lockup p').textContent='THE SKY IS NOT EMPTY.'; screenUi.querySelector('h2').innerHTML='DEFEND<br /><em>THE VECTOR</em>'; startButton.innerHTML='<span>▶</span> 출격 시작'; screenUi.classList.add('hidden'); updateHud(); requestAnimationFrame(loop); }
function updateHud() { scoreEl.textContent=String(game?.score || 0).padStart(6,'0'); highScoreEl.textContent=String(highScore).padStart(6,'0'); waveEl.textContent=String(game?.stage || 1).padStart(2,'0'); shieldEl.textContent=String(Math.max(0, game?.shield || 0)).padStart(2,'0'); weaponEl.textContent=`VECTOR // ${game?.weapon===3?'TRIPLE':game?.weapon===2?'DOUBLE':'SINGLE'}`; if(game?.boss){bossReadout.classList.add('visible');bossNameEl.textContent=`BOSS // STAGE ${game.stage}`;const percent=Math.max(0,Math.ceil(game.boss.hp/game.boss.maxHp*100));bossPercentEl.textContent=`${percent}%`;bossBarFill.style.width=`${percent}%`}else{bossReadout.classList.remove('visible')} }
function spawnEnemy() { const kind=Math.random()<(.22+game.stage*.04)?'heavy':'scout'; const speed=(kind==='heavy'?72:98)+(game.stage-1)*22+game.wave*7; game.enemies.push({kind,x:35+Math.random()*(W-70),y:-35,w:kind==='heavy'?29:20,h:kind==='heavy'?26:18,hp:kind==='heavy'?3:1,speed,phase:Math.random()*Math.PI*2,shot:.7+Math.random()*1.4}); }
function spawnGroundTarget() { game.groundTargets.push({x:35+Math.random()*(W-70),y:-20,w:18+Math.random()*18,h:18+Math.random()*13,hp:1}); }
function spawnBoss() { const maxHp=game.stage===1?25:38;game.boss={x:W/2,y:-70,w:76,h:52,hp:maxHp,maxHp,shot:1.2,phase:0,defeated:false};game.bossSpawned=true;game.enemyBullets=[];game.enemies=[];addText(`STAGE ${game.stage} BOSS`,W/2,220,colors.red); }
function advanceStage() { game.stage+=1;game.elapsed=0;game.wave=1;game.boss=null;game.bossSpawned=false;game.enemyBullets=[];game.enemies=[];game.groundTargets=[];game.pickups=[];addText('STAGE 2 // JUNGLE CORE',W/2,250,colors.mint); }
function defeatBoss() { if(!game.boss||game.boss.defeated)return;game.boss.defeated=true;const defeatedStage=game.stage;game.score+=defeatedStage===1?1000:2500;burst(game.boss.x,game.boss.y,colors.orange,42);addText(defeatedStage===1?'+1000':'FINAL BOSS DOWN',game.boss.x,game.boss.y-30,colors.orange);if(defeatedStage===1)advanceStage();else{game.boss=null;game.active=false;endGame(true)} }
function fire() { if (!game?.active || game.paused || game.player.cooldown>0) return; const spread=game.weapon===3?[-.25,0,.25]:game.weapon===2?[-.16,.16]:[0]; spread.forEach(angle=>game.bullets.push({x:game.player.x+angle*25,y:game.player.y-20,vx:angle*180,vy:-520,r:3})); game.player.cooldown=game.weapon===3?125:160; }
function updateBoss(dt,p) { const boss=game.boss;if(boss.y<105)boss.y+=70*dt;boss.phase+=dt;boss.x=W/2+Math.sin(boss.phase*1.4)*130;boss.shot-=dt;if(boss.shot<=0){[-.35,0,.35].forEach(angle=>game.enemyBullets.push({x:boss.x,y:boss.y+boss.h/2,vx:angle*150+(p.x-boss.x)*.08,vy:145+game.stage*20,r:5}));boss.shot=Math.max(.7,1.35-game.stage*.12)}}
function bomb() { if (!game?.active || game.paused || game.bombFlash>0) return; game.bombFlash=380; game.enemyBullets=[]; game.enemies.forEach(enemy=>{ enemy.hp=0; burst(enemy.x,enemy.y,colors.orange,12); }); game.groundTargets.forEach(target=>{ target.hp=0; burst(target.x,target.y,colors.mint,8); }); game.score+=game.enemies.length*35+game.groundTargets.length*20; addText('BOMB CLEAR',W/2,H/2,colors.orange); }
function movePlayer(dt) { const p=game.player; let dx=0,dy=0; if(keys.ArrowLeft||keys.a)dx--;if(keys.ArrowRight||keys.d)dx++;if(keys.ArrowUp||keys.w)dy--;if(keys.ArrowDown||keys.s)dy++; const length=Math.hypot(dx,dy)||1; p.x=Math.max(22,Math.min(W-22,p.x+dx/length*260*dt));p.y=Math.max(45,Math.min(H-35,p.y+dy/length*260*dt)); }
function update(dt) { if(game.endingMs>0){game.endingMs=Math.max(0,game.endingMs-dt*1000);return} if(!game.active||game.paused)return; game.elapsed+=dt; const p=game.player; movePlayer(dt); p.cooldown=Math.max(0,p.cooldown-dt*1000);p.invincible=Math.max(0,p.invincible-dt*1000);game.bombFlash=Math.max(0,game.bombFlash-dt*1000);if(keys.Space)fire();
  game.enemyTimer-=dt;game.groundTimer-=dt;if(!game.boss&&game.elapsed>=24)spawnBoss();if(!game.boss&&game.enemyTimer<=0){spawnEnemy();game.enemyTimer=Math.max(.22,.62-game.stage*.07-game.wave*.025)} if(!game.boss&&game.groundTimer<=0){spawnGroundTarget();game.groundTimer=Math.max(1.5,2.5-game.stage*.35)+Math.random()*1.2}
  game.wave=Math.min(9,Math.floor(game.elapsed/8)+1);if(game.boss)updateBoss(dt,p);game.stars.forEach(s=>{s.y+=s.v*dt;if(s.y>H)s.y=-2});
  game.bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});game.bullets=game.bullets.filter(b=>b.y>-20&&b.x>-20&&b.x<W+20);
  game.enemyBullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});game.enemyBullets=game.enemyBullets.filter(b=>b.y<H+20);
  game.enemies.forEach(e=>{e.y+=e.speed*dt;e.x+=Math.sin(game.elapsed*2+e.phase)*28*dt;e.shot-=dt;if(e.shot<0){game.enemyBullets.push({x:e.x,y:e.y+e.h,vx:(p.x-e.x)*(.13+game.stage*.025),vy:155+game.stage*20+game.wave*5,r:3});e.shot=Math.max(.7,1.5-game.stage*.18-game.wave*.025)+Math.random()*.8}});game.enemies=game.enemies.filter(e=>e.y<H+50&&e.hp>0);
  game.groundTargets.forEach(t=>t.y+=(75+game.stage*18+game.wave*4)*dt);game.groundTargets=game.groundTargets.filter(t=>t.y<H+30&&t.hp>0);game.pickups.forEach(item=>{item.y+=(62+game.stage*12+game.wave*3)*dt;item.spin+=dt*5});game.pickups=game.pickups.filter(item=>item.y<H+30&&!item.collected);
  hitDetection(); game.particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;q.vy+=30*dt});game.particles=game.particles.filter(q=>q.life>0);game.texts.forEach(t=>{t.y-=28*dt;t.life-=dt});game.texts=game.texts.filter(t=>t.life>0);updateHud(); }
function dropMissileItem(enemy) { if(enemy.kind==='heavy'&&Math.random()<.72) game.pickups.push({x:enemy.x,y:enemy.y,spin:0,collected:false}); }
function collectMissileItem(item) { item.collected=true;game.weapon=Math.min(3,game.weapon+1);game.score+=100;burst(item.x,item.y,colors.mint,16);addText(game.weapon===3?'MISSILE // TRIPLE':'MISSILE UPGRADE',item.x,item.y-15,colors.mint); }
function checkBossHits() { if(!game.boss)return;game.bullets.forEach(b=>{if(game.boss&&!game.boss.defeated&&dist(b,game.boss)<game.boss.w*.85){game.boss.hp--;b.y=-50;burst(b.x,b.y,colors.blue,3);if(game.boss.hp<=0)defeatBoss()}}); }
function hitDetection() { const p=game.player;checkBossHits();game.bullets.forEach(b=>{game.enemies.forEach(e=>{if(e.hp>0&&dist(b,e)<e.w){e.hp--;b.y=-50;burst(e.x,e.y,e.hp?colors.blue:colors.orange,e.hp?4:12);if(!e.hp){game.score+=e.kind==='heavy'?150:50;if(e.kind==='heavy')dropMissileItem(e);addText(e.kind==='heavy'?'+150':'+50',e.x,e.y,colors.orange)}}});game.groundTargets.forEach(t=>{if(t.hp>0&&dist(b,t)<t.w){t.hp=0;b.y=-50;game.score+=80;burst(t.x,t.y,colors.mint,10);addText('+80',t.x,t.y,colors.mint)}})}); game.pickups.forEach(item=>{if(!item.collected&&dist(item,p)<22)collectMissileItem(item)}); game.enemyBullets.forEach(b=>{if(dist(b,p)<18){b.y=H+50;if(p.invincible<=0){game.shield--;p.invincible=1600;burst(p.x,p.y,colors.red,22);addText('SHIELD HIT',p.x,p.y-25,colors.red);if(game.shield<=0){game.active=false;endGame()}}}}); game.enemies.forEach(e=>{if(e.hp>0&&dist(e,p)<20){e.hp=0;if(p.invincible<=0){game.shield--;p.invincible=1600;burst(p.x,p.y,colors.red,22)}}}); }
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function burst(x,y,color,count){for(let i=0;i<count;i++){const angle=Math.random()*Math.PI*2,speed=Math.random()*100+35;game.particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:.3+Math.random()*.5,color})}}
function addText(text,x,y,color){game.texts.push({text,x,y,color,life:1})}
function draw() {ctx.fillStyle='#071215';ctx.fillRect(0,0,W,H);drawBackground();game.groundTargets.forEach(drawGround);game.pickups.forEach(drawPickup);game.enemies.forEach(drawEnemy);if(game.boss)drawBoss(game.boss);game.bullets.forEach(drawBullet);game.enemyBullets.forEach(b=>drawEnemyBullet(b));game.particles.forEach(q=>{ctx.globalAlpha=Math.max(0,q.life/.7);ctx.fillStyle=q.color;ctx.fillRect(q.x,q.y,3,3)});ctx.globalAlpha=1;drawPlayer();game.texts.forEach(t=>{ctx.globalAlpha=t.life;ctx.fillStyle=t.color;ctx.font='bold 14px Space Mono, monospace';ctx.textAlign='center';ctx.fillText(t.text,t.x,t.y)});ctx.globalAlpha=1;if(game.bombFlash>0){ctx.fillStyle=`rgba(142,245,218,${game.bombFlash/800})`;ctx.fillRect(0,0,W,H)} }
function drawBackground(){const stageTwo=game.stage===2;const gradient=ctx.createLinearGradient(0,0,0,H);if(stageTwo){gradient.addColorStop(0,'#351b2c');gradient.addColorStop(.52,'#6b302d');gradient.addColorStop(1,'#170d19')}else{gradient.addColorStop(0,'#102f2a');gradient.addColorStop(.52,'#1b4934');gradient.addColorStop(1,'#071b1d')}ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);const scroll=(game.elapsed*42)%140;ctx.globalAlpha=.32;for(let y=-140+scroll;y<H+140;y+=140){ctx.fillStyle=stageTwo?'#3e1d27':'#0a2924';ctx.beginPath();if(stageTwo){ctx.moveTo(0,y+140);ctx.lineTo(55,y+76);ctx.lineTo(105,y+110);ctx.lineTo(165,y+35);ctx.lineTo(238,y+92);ctx.lineTo(305,y+50);ctx.lineTo(372,y+118);ctx.lineTo(430,y+66);ctx.lineTo(480,y+100)}else{ctx.moveTo(0,y+80);ctx.lineTo(68,y+25);ctx.lineTo(125,y+70);ctx.lineTo(182,y+15);ctx.lineTo(250,y+85);ctx.lineTo(318,y+28);ctx.lineTo(390,y+72);ctx.lineTo(480,y+20)}ctx.lineTo(480,y+140);ctx.lineTo(0,y+140);ctx.fill()}ctx.globalAlpha=.25;for(let x=-30;x<W+60;x+=74){ctx.fillStyle=stageTwo?(x%148===0?'#b44b38':'#71302e'):(x%148===0?'#70a84f':'#3b7c42');ctx.fillRect(x,0,8,H);ctx.beginPath();ctx.moveTo(x+4,0);ctx.quadraticCurveTo(x-20,80,x+18,150);ctx.quadraticCurveTo(x+52,220,x+5,300);ctx.strokeStyle=stageTwo?'#d56a45':'#89ba58';ctx.stroke()}ctx.globalAlpha=.55;game.stars.forEach(s=>{s.y+=s.v*.015;ctx.fillStyle=stageTwo?(s.a>.72?'#ffd18b':'#d76a54'):(s.a>.72?'#b6dc83':'#4d9660');ctx.fillRect(s.x,s.y%H,s.s+1,s.s+1)});ctx.globalAlpha=1;ctx.strokeStyle=stageTwo?'rgba(255,155,91,.12)':'rgba(142,245,218,.09)';ctx.lineWidth=1;for(let y=(game.elapsed*50)%45;y<H;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function drawPlayer(){const p=game.player;if(p.invincible>0&&Math.floor(p.invincible/100)%2===0)return;ctx.save();ctx.translate(p.x,p.y);ctx.shadowBlur=18;ctx.shadowColor=colors.mint;ctx.fillStyle=colors.mint;ctx.beginPath();ctx.moveTo(0,-23);ctx.lineTo(10,14);ctx.lineTo(0,9);ctx.lineTo(-10,14);ctx.closePath();ctx.fill();ctx.fillStyle=colors.orange;ctx.beginPath();ctx.moveTo(-5,13);ctx.lineTo(0,25+Math.random()*5);ctx.lineTo(5,13);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#122f35';ctx.fillRect(-3,-7,6,9);ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.shadowBlur=12;ctx.shadowColor=e.kind==='heavy'?colors.red:colors.orange;ctx.fillStyle=e.kind==='heavy'?colors.red:colors.orange;ctx.beginPath();ctx.moveTo(0,e.h/2);ctx.lineTo(-e.w/2,-e.h/3);ctx.lineTo(-e.w/5,-e.h/2);ctx.lineTo(0,-e.h/4);ctx.lineTo(e.w/5,-e.h/2);ctx.lineTo(e.w/2,-e.h/3);ctx.closePath();ctx.fill();ctx.fillStyle='#07151a';ctx.fillRect(-4,-3,8,5);ctx.restore()}
function drawBoss(boss){ctx.save();ctx.translate(boss.x,boss.y);ctx.shadowBlur=24;ctx.shadowColor=colors.red;ctx.fillStyle=colors.red;ctx.beginPath();ctx.moveTo(0,boss.h/2);ctx.lineTo(-boss.w/2,-boss.h/3);ctx.lineTo(-boss.w/3,-boss.h/2);ctx.lineTo(0,-boss.h/4);ctx.lineTo(boss.w/3,-boss.h/2);ctx.lineTo(boss.w/2,-boss.h/3);ctx.closePath();ctx.fill();ctx.fillStyle=colors.orange;ctx.fillRect(-boss.w/4,-5,boss.w/2,10);ctx.fillStyle='#07151a';ctx.fillRect(-8,-3,16,6);ctx.restore()}
function drawGround(t){ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='#c27762';ctx.shadowBlur=9;ctx.shadowColor=colors.orange;ctx.fillRect(-t.w/2,-t.h/2,t.w,t.h);ctx.fillStyle='#07151a';ctx.fillRect(-t.w/4,-t.h/4,t.w/2,t.h/2);ctx.restore()}
function drawPickup(item){ctx.save();ctx.translate(item.x,item.y);ctx.rotate(item.spin);ctx.shadowBlur=18;ctx.shadowColor=colors.mint;ctx.fillStyle=colors.mint;ctx.beginPath();ctx.moveTo(0,-13);ctx.lineTo(13,0);ctx.lineTo(0,13);ctx.lineTo(-13,0);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#0b302d';ctx.fillRect(-7,-3,14,6);ctx.fillStyle=colors.orange;ctx.fillRect(-2,-7,4,14);ctx.restore()}
function drawBullet(b){ctx.fillStyle=colors.mint;ctx.shadowBlur=10;ctx.shadowColor=colors.mint;ctx.fillRect(b.x-2,b.y-9,4,13);ctx.shadowBlur=0}function drawEnemyBullet(b){ctx.fillStyle=colors.red;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()}
function endGame(victory=false){if(game.score>highScore){highScore=game.score;localStorage.setItem('sky-vector-high-score',String(game.score))}if(victory)game.endingMs=10000;screenUi.classList.toggle('victory',victory);screenUi.classList.remove('hidden');screenUi.querySelector('.screen-tag').textContent=victory?'MISSION // COMPLETE':'MISSION // SIGNAL LOST';screenUi.querySelector('.title-lockup p').textContent=victory?`두 스테이지 방어 성공 // ${String(game.score).padStart(6,'0')} POINTS`:`FINAL SCORE // ${String(game.score).padStart(6,'0')}`;screenUi.querySelector('h2').innerHTML=victory?'SKYLINE<br /><em>SECURED</em>':'SECTOR<br /><em>FALLEN</em>';startButton.innerHTML='<span>↻</span> 다시 출격';}
function loop(time){if(!game)return;const dt=Math.min(.033,(time-(game.lastTime||time))/1000);game.lastTime=time;update(dt);draw();if(game.active||game.endingMs>0)requestAnimationFrame(loop)}
startButton.addEventListener('click',startGame);document.addEventListener('keydown',e=>{keys[e.key]=true;if(e.code==='Space'){e.preventDefault();keys.Space=true}if(e.key.toLowerCase()==='x')bomb();if(e.key.toLowerCase()==='p'&&game?.active)game.paused=!game.paused});document.addEventListener('keyup',e=>{keys[e.key]=false;if(e.code==='Space')keys.Space=false});document.querySelectorAll('[data-action]').forEach(button=>{button.addEventListener('pointerdown',()=>{const action=button.dataset.action;if(action==='fire')keys.Space=true;else if(action==='bomb')bomb();else keys[{left:'ArrowLeft',right:'ArrowRight',up:'ArrowUp',down:'ArrowDown'}[action]]=true});button.addEventListener('pointerup',()=>{const action=button.dataset.action;if(action==='fire')keys.Space=false;else keys[{left:'ArrowLeft',right:'ArrowRight',up:'ArrowUp',down:'ArrowDown'}[action]]=false});button.addEventListener('pointercancel',()=>{if(button.dataset.action==='fire')keys.Space=false})});
